name: Pluto Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: Anacoder001
          outputs: |
            dist/snake.svg
            dist/pluto-snake.svg?color_snake=#00FF41&color_dots=#0d1117,#003300,#00FF41,#33FF66,#66FF99
            dist/pluto-snake.gif?color_snake=#00FF41&color_dots=#0d1117,#003300,#00FF41,#33FF66,#66FF99
            dist/pluto-snake-dark.svg?color_snake=#00FF41&color_dots=#66FF99,#33FF66,#00FF41,#003300,#0d1117

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
